input.onButtonPressed(Button.A, function () {
    led.enable(false)
    pins.digitalWritePin(DigitalPin.P3, 1)
    pins.digitalWritePin(DigitalPin.P3, 0)
    for (let index = 0; index < 2; index++) {
        pins.analogWritePin(AnalogPin.P3, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P3, 0)
        pins.analogWritePin(AnalogPin.P4, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P4, 0)
        pins.analogWritePin(AnalogPin.P5, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P5, 0)
        pins.analogWritePin(AnalogPin.P6, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P6, 0)
        pins.analogWritePin(AnalogPin.P3, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P3, 0)
        pins.analogWritePin(AnalogPin.P4, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P4, 0)
        pins.analogWritePin(AnalogPin.P5, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P5, 0)
        pins.analogWritePin(AnalogPin.P6, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P6, 0)
        basic.pause(1000)
        pins.analogWritePin(AnalogPin.P6, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P6, 0)
        pins.analogWritePin(AnalogPin.P3, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P3, 0)
        pins.analogWritePin(AnalogPin.P4, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P4, 0)
        pins.analogWritePin(AnalogPin.P5, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P5, 0)
        pins.analogWritePin(AnalogPin.P6, 1023)
        basic.pause(1000)
        pins.analogWritePin(AnalogPin.P6, 0)
    }
    basic.clearScreen()
})
input.onButtonPressed(Button.AB, function () {
    basic.showLeds(`
        . . . . .
        . . # . .
        . # . # .
        . . # . .
        . . . . .
        `)
    basic.showIcon(IconNames.Happy)
    basic.showIcon(IconNames.SmallHeart)
    basic.showIcon(IconNames.Heart)
    basic.showLeds(`
        . . . . .
        . . # . .
        . # . # .
        . . # . .
        . . . . .
        `)
    for (let index = 0; index < 2; index++) {
        pins.analogWritePin(AnalogPin.P0, 1023)
        pins.analogWritePin(AnalogPin.P1, 33)
        pins.analogWritePin(AnalogPin.P2, 91)
        pins.analogWritePin(AnalogPin.P8, 206)
        basic.pause(1000)
        basic.showIcon(IconNames.Diamond)
        pins.analogWritePin(AnalogPin.P0, 0)
        pins.analogWritePin(AnalogPin.P1, 0)
        pins.analogWritePin(AnalogPin.P2, 0)
        pins.analogWritePin(AnalogPin.P8, 0)
    }
    for (let index = 0; index < 2; index++) {
        basic.showIcon(IconNames.Happy)
        pins.analogWritePin(AnalogPin.P8, 1023)
        pins.analogWritePin(AnalogPin.P2, 173)
        pins.analogWritePin(AnalogPin.P1, 248)
        pins.analogWritePin(AnalogPin.P0, 132)
        basic.pause(2000)
        pins.analogWritePin(AnalogPin.P8, 0)
        pins.analogWritePin(AnalogPin.P2, 0)
        pins.analogWritePin(AnalogPin.P1, 0)
        pins.analogWritePin(AnalogPin.P0, 0)
    }
    for (let index = 0; index < 1; index++) {
        basic.showIcon(IconNames.Happy)
        pins.analogWritePin(AnalogPin.P8, 900)
        pins.analogWritePin(AnalogPin.P2, 429)
        pins.analogWritePin(AnalogPin.P1, 644)
        pins.analogWritePin(AnalogPin.P0, 627)
        basic.pause(2000)
        pins.analogWritePin(AnalogPin.P8, 0)
        pins.analogWritePin(AnalogPin.P2, 0)
        pins.analogWritePin(AnalogPin.P1, 0)
        pins.analogWritePin(AnalogPin.P0, 0)
        basic.showString("Good Bye!")
        basic.showIcon(IconNames.Happy)
        basic.clearScreen()
    }
})
input.onButtonPressed(Button.B, function () {
    led.enable(false)
    for (let index = 0; index < 4; index++) {
        pins.analogWritePin(AnalogPin.P3, randint(100, 500))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P3, 0)
        pins.analogWritePin(AnalogPin.P4, randint(100, 500))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P4, 0)
        pins.analogWritePin(AnalogPin.P5, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P5, 0)
        pins.analogWritePin(AnalogPin.P6, randint(500, 1000))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P6, 0)
        pins.analogWritePin(AnalogPin.P3, randint(100, 500))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P3, 0)
        pins.analogWritePin(AnalogPin.P4, randint(0, 100))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P4, 0)
        pins.analogWritePin(AnalogPin.P5, randint(500, 800))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P5, 0)
        pins.analogWritePin(AnalogPin.P6, randint(500, 800))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P6, 0)
        basic.pause(1000)
        pins.analogWritePin(AnalogPin.P6, randint(500, 800))
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P6, 0)
        pins.analogWritePin(AnalogPin.P3, 190)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P3, 0)
        pins.analogWritePin(AnalogPin.P4, 388)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P4, 0)
        pins.analogWritePin(AnalogPin.P5, 627)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P5, 0)
        pins.analogWritePin(AnalogPin.P6, 1023)
        basic.pause(200)
        pins.analogWritePin(AnalogPin.P6, 0)
    }
    basic.clearScreen()
})
basic.showString("Hello!")
basic.forever(function () {
	
})
